# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'CV',   url: 'about.html'}
- {name: 'Publication', url: 'writing.html'}
- {name: 'Leadership', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'orcid',     link: 'https://orcid.org/my-orcid?orcid=0000-0003-0810-0930'}
- {icon: 'google',    link: 'https://scholar.google.com/citations?user=mmXr068AAAAJ&hl=zh-CN'}
- {icon: 'graduation-cap',   link: 'https://www.researchgate.net/profile/Yuanyuan-Song-2'}
